name: checkjson
run-name: Commit to ${{ inputs.deploy_target }} by @${{ github.actor }}
on: [push]
jobs:
  check-json-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      with: 
        path: './config/'
      - run: |
        echo Hello from Workflow