name: Validate JSONs

on: [push]

jobs:
  validate-jsons:
    strategy:
      matrix:
        schema: [effectschema.json, entityschema.json, levelschema.json, itemschema.json]
        json: [effects.json, entities.json, levels.json, items.json]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /.github/workflows/${{ matrix.schema }}
          INPUT_JSONS: /config/${{ matrix.json }}