name: Validate JSONs

on:
  push:
    branches:
      - main
jobs:
  validate-jsons:
    strategy:
      matrix:
          json: ['effects', 'entities', 'levels', 'items']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate Levels JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /.github/workflows/${{matrix.json}}chema.json
          INPUT_JSONS: /config/${{matrix.json}}.json
