name: Validate JSONs

on:
  push:
    branches:
      - main

jobs:
  validate-jsons:
    strategy:
      matrix:
          schema: ['effects', 'entities', 'levels', 'items']
          json: ['effects', 'entities', 'levels', 'items']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache ajv-cli
        uses: actions/cache@v2
        with:
          path: ${{ env.HOME }}/.npm-global/bin/ajv
          key: ${{ runner.os }}-ajv-${{ env.IMAGE_VERSION }}
          restore-keys: ${{ runner.os }}-ajv-

      - name: Install Ajv-cli
        run: |
          if ! command -v ajv &> /dev/null; then
            npm install -g ajv-cli
          fi

      - name: Validate JSON
        env:
          AJV_PATH: ${{ env.HOME }}/.npm-global/bin/ajv
        run: ajv validate -s "/.github/workflows/${{ matrix.schema }}.json" -d "/config/${{ matrix.json }}.json" --all-errors
