name: Validate JSONs

on:
  pull_request:
    branches:
      - main

jobs:
  validate-jsons:
    strategy:
      matrix:
          json: ['Effects', 'Entities', 'Levels', 'Items']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: true
          fetch-depth: 0
          schema: /.github/workflows/${{matrix.json}}chema.json
          jsons: /Assets/Core/${{matrix.json}}/**.json
      - name: Validate JSON
        uses: nhalstead/validate-json-action@0.1.3